apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: dalareo/notes-app:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install psycopg2
          pip list
          python -c "import opentelemetry; print(opentelemetry.__version__)"
          python -m django --version
          python manage.py check
          python manage.py runserver 0.0.0.0:8000
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: notes
        - name: DB_USER
          value: django
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy.grafana.svc.cluster.local:4317"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: notes
        - name: POSTGRES_USER
          value: django
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: OTEL_SERVICE_NAME
          value: postgresql-service
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy.grafana.svc.cluster.local:4317"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app
spec:
  selector:
    app: notes-app
  ports:
  - port: 8000
    targetPort: 8000
